### ISSUE TITLE
Any thoughts on license?

### ISSUE THREAD

**Issue by lasagnaphil** [Omegastick/pytorch-cpp-rl#12]
Greetings,

Right now I'm trying to implement RL algorithms with the physics engine (PhysX) as the environment, while avoiding bindings between C++ and Python. As there aren't that many projects using the libtorch C++ frontend, this repo has been really helpful to people like me. However, I noticed that there wasn't any mentioning of a license, so it made me anxious about using parts of the code (Note that without an explicit license, formally Github users only have the right to fork or read the code, and other than that typical copyright laws hold.) Any thoughts about license? (Nowadays most people choose MIT as their license because it doesn't have any strings attached, but other licenses are also fine; it's your choice.)

Best regards,
Phil

**Comment by Omegastick** [comment]
Huh, I could swear I added a license. It must have been in a branch. I've put in the MIT license now.
