### ISSUE TITLE
When build under Ubuntu 18 have error "error: ‘double torch::optim::RMSpropOptions::learning_rate_’ is private within this context..""

### ISSUE THREAD

**Issue by geotyper** [Omegastick/pytorch-cpp-rl#16]
In member function ‘virtual std::vector<cpprl::UpdateDatum> cpprl::A2C::update(cpprl::RolloutStorage&, float)’:
/home/geotyper/CPP_torch/pytorch-cpp-rl-master/src/algorithms/a2c.cpp:39:24: error: ‘double torch::optim::RMSpropOptions::learning_rate_’ is private within this context
     optimizer->options.learning_rate_ = original_learning_rate * decay_level;

**Comment by Omegastick** [comment]
Just got this error on the Windows CI build, but not the Ubuntu one. It's building fine on my home PCs too. Looking into it now.

Maybe an incompatibility with PyTorch 1.3?

**Comment by Omegastick** [comment]
Looks like https://github.com/pytorch/pytorch/commit/ce3d024727c26bce37103c731cb3f5521bf0ab23 broke it. I'll get a fix up once I've built PyTorch 1.3 on my PC.

**Comment by geotyper** [comment]
found that if change to
 optimizer->options.learning_rate(original_learning_rate * decay_level); //options.learning_rate_
compiles without errors

**Comment by Omegastick** [comment]
Should be fixed in e1844a17427c319f2c823f2a51dfb22e5d8094cf.
