### ISSUE TITLE
Error in python server "module 'gym.envs.box2d' has no attribute 'LunarLander'"

### ISSUE THREAD

**Issue by geotyper** [Omegastick/pytorch-cpp-rl#17]
![image](https://user-images.githubusercontent.com/30755433/67112962-185a0880-f1e1-11e9-83c2-e0bfb7b98460.png)

**Comment by Omegastick** [comment]
Did you do `pip install gym[box2d]`?

**Comment by geotyper** [comment]
Understand/ but no time till
Write about results on next week

пт, 18 окт. 2019 г. в 21:34, Isaac Poulton <notifications@github.com>:

**Comment by geotyper** [comment]
Understand/ but no time till Monday
Write about results on next week

**Comment by geotyper** [comment]
![image](https://user-images.githubusercontent.com/30755433/67157441-d80b9f00-f334-11e9-81db-21e64a041b24.png)
works! )
