### ISSUE TITLE
consider using CMake's built in cppcheck support

### ISSUE THREAD

**Issue by billhoffman** [Omegastick/pytorch-cpp-rl#5]
https://github.com/Omegastick/pytorch-cpp-rl/blob/b4a244ebdff7bb7760d5c62f04e5bc93ecee619d/CMakeLists.txt#L12

You might want to consider using the built in cmake support for cppcheck:
https://blog.kitware.com/static-checks-with-cmake-cdash-iwyu-clang-tidy-lwyu-cpplint-and-cppcheck/

**Comment by Omegastick** [comment]
I was using that before, but I didn't like that it runs by default (it can take a while to run sometimes). Is there a way to use the built in support but still have running it be "opt-in"?

**Comment by Omegastick** [comment]
Gonna close this for now, because a seperate `make check` command is cleaner IMO.
